### ISSUE TITLE
Issue Categorizing with BlueCoat

### ISSUE THREAD

**Issue by rj4yb3** [mdsecactivebreach/Chameleon#1]
I've successfully categorized a few sites with McAfee and IBM but keep getting the following error with BlueCoat:

```
[-] Targeting Bluecoat WebPulse
[-] WARNING: This module must be run from the webserver you want to categorise
[-] Proceed: Y/N
Y
[-] Cloning https://www.bankofamerica.com
Traceback (most recent call last):
  File "chameleon.py", line 72, in <module>
    c.run(args)
  File "chameleon.py", line 55, in run
    b.run()
  File "/home/tools/Chameleon/modules/bluecoat.py", line 95, in run
    self.clone()
  File "/home/tools/Chameleon/modules/bluecoat.py", line 55, in clone
    with open('webroot/index.html', 'w') as indexFile:
IOError: [Errno 2] No such file or directory: 'webroot/index.html'
```

Did some limited troubleshooting and had no luck.

**Comment by michael-bey** [comment]
If you're doing this from ubuntu, change this and line 55 to be /var/www

**Comment by mdsecactivebreach** [comment]
You just need to mkdir webroot - git didn't push the empty directory.
